import { jsPDF } from "jspdf";
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const TEAL: [number, number, number] = [0, 100, 124];
export const LIGHT: [number, number, number] = [240, 249, 251];
export const MUTED: [number, number, number] = [110, 110, 110];
export const INK: [number, number, number] = [40, 40, 40];

export const MARGIN = 14;
export const PAGE_W = 210;
export const PAGE_H = 297;
export const CONTENT_W = PAGE_W - 2 * MARGIN;

export interface BusinessInfo {
  name: string;
  tagline?: string;
  phone: string;
  email: string;
  website: string;
}

export function loadPngDataUrl(file: string): string {
  const buf = readFileSync(join(process.cwd(), "public", file));
  return `data:image/png;base64,${buf.toString("base64")}`;
}

export function sectionTitle(doc: jsPDF, text: string, x: number, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...TEAL);
  doc.text(text.toUpperCase(), x, y);
}

export function wrapLines(doc: jsPDF, text: string, width: number, max: number): string[] {
  if (!text) return [];
  const lines = doc.splitTextToSize(text, width) as string[];
  return lines.slice(0, max).map(String);
}

/** Branded white header: Glymee logo mark + name on left, contact block on right, divider beneath. */
export function brandHeader(doc: jsPDF, business: BusinessInfo) {
  try {
    doc.addImage(loadPngDataUrl("Glymee_logo_1.png"), "PNG", MARGIN, 10.5, 12.4, 11.8);
    doc.addImage(loadPngDataUrl("Glymee_name.png"), "PNG", MARGIN + 15.5, 11, 42, 11.3);
  } catch {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...TEAL);
    doc.text("GLYMEE HEALTH", MARGIN, 20);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Phone: ${business.phone}`, PAGE_W - MARGIN, 15, { align: "right" });
  doc.text(`Email: ${business.email}`, PAGE_W - MARGIN, 21.5, { align: "right" });
  doc.text(business.website, PAGE_W - MARGIN, 28, { align: "right" });

  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, 44, PAGE_W - MARGIN, 44);
}

/** Multi-line section heading (teal bold, e.g. "C. GLUCOSE OVERVIEW"). Returns y after heading. */
export function sectionHeading(doc: jsPDF, text: string, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...TEAL);
  doc.text(text, MARGIN, y);
  return y + 5.5;
}

/** Wrapped text paragraph at 9pt/4.6 line height. Returns y after paragraph; skips if empty. */
export function paragraph(doc: jsPDF, text: string, y: number, opts?: { size?: number; indent?: string }) {
  if (!text) return y;
  const lines = doc.splitTextToSize(text, CONTENT_W) as string[];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(opts?.size || 9);
  doc.setTextColor(...INK);
  for (const line of lines) {
    doc.text(`${opts?.indent || ""}${line}`, MARGIN, y);
    y += 4.6;
  }
  return y + 1.5;
}

/** Bulleted list (each bullet the starting character of the line, e.g. "● "). Empty lines become spacing. */
export function bulletList(doc: jsPDF, text: string, y: number, bullet = "• ") {
  if (!text) return y;
  const items = text.split("\n").map((s) => s.trim()).filter(Boolean);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  for (const item of items) {
    const lines = doc.splitTextToSize(item, CONTENT_W - 8) as string[];
    lines.forEach((line, i) => {
      doc.text(i === 0 ? `${bullet}${line}` : `   ${line}`, MARGIN, y);
      y += 4.6;
    });
  }
  return y + 1.5;
}

/** Label/value pair rendered inline ("R1" label + wrapped value). */
export function kvLine(doc: jsPDF, label: string, value: string, y: number) {
  const labelW = 34;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  doc.text(label, MARGIN, y);
  if (!value) return y + 5.5;
  const lines = doc.splitTextToSize(value, CONTENT_W - labelW - 2) as string[];
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED);
  lines.forEach((line, i) => {
    doc.text(line as string, MARGIN + labelW, y + i * 4.6);
  });
  return y + lines.length * 4.6 + 1.2;
}

/** Footer on every page: "Generated by Glymee", disclaimer, page numbers. Call before returning buffer. */
export function brandFooter(doc: jsPDF, extra?: { generatedFor?: string }) {
  const disclaimer =
    "This report is generated by Glymee, a diabetes health management platform, and is intended for informational purposes. It does not replace professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.";
  const footer = (page: number) => {
    doc.setPage(page);
    doc.setDrawColor(210, 210, 210);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_H - 14.5, PAGE_W - MARGIN, PAGE_H - 14.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    const note = extra?.generatedFor
      ? `Prepared by Glymee for ${extra.generatedFor}.`
      : "Prepared by Glymee.";
    const lines = doc.splitTextToSize(`${note} ${disclaimer}`, PAGE_W - 40) as string[];
    let ly = PAGE_H - 11.5;
    lines.slice(0, 2).forEach((line) => {
      doc.text(line as string, PAGE_W / 2, ly, { align: "center" });
      ly += 3.4;
    });
    doc.setFontSize(7.5);
    doc.text(`Page ${page} of ${doc.getNumberOfPages()}`, PAGE_W - MARGIN, PAGE_H - 7, {
      align: "right",
    });
    doc.text("Glymee Health", MARGIN, PAGE_H - 7);
  };

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    footer(p);
  }
}

/** Returns a fresh A4 doc with the branded header applied and y positioned after it. */
export function createReportDoc(business: BusinessInfo): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  brandHeader(doc, business);
  return doc;
}

/** Draws a soft box with a section title; returns the starting content y inside it. */
export function softBox(doc: jsPDF, title: string, x: number, y: number, w: number, h: number) {
  doc.setFillColor(...LIGHT);
  doc.roundedRect(x, y, w, h, 2, 2, "F");
  sectionTitle(doc, title, x + 5, y + 7);
  return y + 13;
}